config/routes.rb
Rails.application.routes.draw do
  #Viwe principal de la pagina
  root 'home#index'
  #Logica de codigo 
  resources :codes
  #View de autenticacion
  devise_for :administrators
  devise_for :users
  #View de Head
  get 'westcoast'  => 'westcoast#westcoast'
  get 'drink'  => 'drink#drink'
  get 'clothes'  => 'clothes#clothes'
  get 'experience'  => 'experience#experience'
  get 'administrator'  => 'administrator#administrator'
 
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
    before_action :authenticate_administrator!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  
   before_action :set_code, only: [:show, :edit, :update, :destroy]

  # GET /codes
  # GET /codes.json
  def index
    @q = params[:q]
    @code = Code.where(:code => @q)
  end

  # GET /codes/1
  # GET /codes/1.json
  def show
  end

  # GET /codes/new
  def new
    @code = Code.new
  end

  # GET /codes/1/edit
  def edit
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(code_params)

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render :show, status: :created, location: @code }
      else
        format.html { render :new }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /codes/1
  # PATCH/PUT /codes/1.json
  def update
    respond_to do |format|
      if @code.update(code_params)
        format.html { redirect_to @code, notice: 'Code was successfully updated.' }
        format.json { render :show, status: :ok, location: @code }
      else
        format.html { render :edit }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
    @code.destroy
    respond_to do |format|
      format.html { redirect_to codes_url, notice: 'Code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code
      @code = Code.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def code_params
      params.require(:code).permit(:code, :description)
    end
end

app/controllers/drink_controller.rb
class DrinkController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/westcoast_controller.rb
class WestcoastController < ApplicationController
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/drink_helper.rb
module DrinkHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/westcoast_helper.rb
module WestcoastHelper
end

app/views/administrator/administrator.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil</title>
</head>

<body>
<br>
<br>
<br>
<br>
<br>
<br>
    <div class="container-fluid">
        <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-primary">
            <div class="col-md p-lg mx-auto my">
                <h1 class="display-4 font-weight-normal">Hola!, <%= current_administrator.email %> Ahora cuentas con
                    permisos de administrador</h1>
            </div>
        </div>


        <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
            <div class="col-md p-lg mx-auto my">
                <h2 class="display-3">New code</h2>
                <%= link_to "New code for products", new_code_path, class:"btn btn-success btn-user" %>
            </div>
        </div>
    </div>

</body>

</html>

app/views/clothes/clothes.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clothes</title>
</head>
<body>
    <br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
    <section class="jumbotron text-center  bg-light">
        <div class="container-fluid">
          <h1 class="jumbotron-heading">Products of West Coast</h1>
          <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
         
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                
                <%= image_tag("2.jpeg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
               
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
           
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <%= image_tag("4.jpeg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>

           

</body>
</html>

app/views/codes/_form.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width new code, initial-scale=1.0">
  <title>New Code</title>
</head>

<body>
  <%= form_with(model: code, local: true) do |form| %>
  <% if code.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(code.errors.count, "error") %> prohibited this code from being saved:</h2>
    <ul>
      <% code.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="card bg-light">
    <div class="row">
      <div class="col-md-5 order-md-1">
        <%= image_tag("pollo.jpg", style: "width: 500px;")%>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <div class="text-center">
            <h1 class="text-gray-900 mb-4">Bienvenido!</h1>
          </div>
          <div class="field">
            <h1 class="font-weight-bold"><%= form.label :code %></h1>
            <%= form.text_field :code, class:"form-control form-control-user" %>
          </div>
          <div class="field">
            <h1 class="font-weight-bold"><%= form.label :description %></h1>
            <%= form.text_area :description, class:"form-control form-control-user" %>
          </div>
          <br>
          <br>
          <div class="actions">
            <%= form.submit class:"btn btn-primary btn-user btn-block"%>
          </div>
          <% end %>
          <br>
          <br>
          <br>
          <%= link_to 'Back', codes_path, class:"btn btn-primary btn-user btn-block" %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/codes/edit.html.erb
<h1>Editing Code</h1>

<%= render 'form', code: @code %>

<%= link_to 'Show', @code %> |
<%= link_to 'Back', codes_path %>

app/views/codes/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br><br>
<br>
<br>
<br>
<br>
<h1>Please get into your code </h1>
<br>
<br>
<br>
<br>
<form>
 <input name="q" <%= @q %> >
 <button type="submit">Buscar</button>
</form>

  <tbody>
  
  <% if @code.empty? %>
    <tr>
    <td>No se encontro su codigo</td>
    </tr>
    <% else %>
    
  
  
    <% @code.each do |code| %>
      <tr>
        <td><%= code.code %></td>
        <td><%= code.description %></td>
        </tr>
    <% end %>
    <% end %>
  </tbody>


<br>

<%= link_to 'New Code', new_code_path %>

app/views/codes/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New code</title>
</head>

<body>
    

    <%= render 'form', code: @code %>

    
</body>

</html>

app/views/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @code.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @code.description %>
</p>

<%= link_to 'Edit', edit_code_path(@code) %> |
<%= link_to 'Back', codes_path %>

app/views/drink/drink.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Drink</title>
</head>

<body>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <section class="jumbotron text-center  bg-light">
    <div class="container-fluid">
      <h1 class="jumbotron-heading font-weight-bold">Drinks of West Coast</h1>


    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">

        <div class="col-md-4">
          <div class="card mb-4 box-shadow">

            <%= image_tag("drinks/1.jpg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>

            <div class="card-body">
              <h2>Vodka Absolut Elyx</h2>
              <p class="card-text">Absolut Elyx is a luxury vodka. The main ingredients are winter wheat and pristine
                water. It has a clean and fresh flavor, with subtle floral and fruity tones, and a texture that is
                determined by how vodka feels in the mouth.
                <br> Its content is 42% alcohol and is usually taken in a wide glass with ice, decorated with a strip of
                freshly cut lemon peel or star anise.</p>
              <h4 class="card-text text-center">€45EUR</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag("drinks/2.jpg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 485px; width: 100%; display: block;" )%>
            <div class="card-body">
              <h2>Vodka Ciroc</h2>
              <p class="card-text">Cîroc vodka is an Ultra-Premium Vodka, it was created in 2003 in the south of France
                and we are talking about one of the few vodkas in the world that is made with the best French grapes
                instead of using the typical cereals. It is a luxury vodka, exquisite, elegantly smooth and
                sophisticated.</p>
              <br>
              <br>
              <h4 class="card-text text-center">€30EUR</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag("drinks/3.jpg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
            <div class="card-body">
              <h2>Belvedere Vodka</h2>
              <p class="card-text">Belvedere Vodka is a super premium vodka created based on the Polish tradition of
                more than 600 years in the purest traditional Polish style.
                <br> 700 milliliters of an impeccable presentation in glass, with 1.2 kilograms. Distilled and filtered
                to create a pure flavor that will impress your palate, it is a product that you should not stop buying.
                You'll love it.</p>

              <h4 class="card-text text-center">€39EUR</h4>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag("drinks/4.jpg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
            <div class="card-body">
              <h2>Johnnie Walker</h2>
              <p class="card-text">Since 1820 this whiskey has been proudly walking the name of the Scottish region of
                Kilmarnock. With almost two centuries of life, many are the children that this distillery has generated
                in the form of bottles, from its icon; Johnnie Walker Red Label.</p>

              <h4 class="card-text text-center">€50EUR</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag("drinks/5.jpg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
            <div class="card-body">
              <h2>Jack Daniels</h2>
              <p class="card-text">The three cereals that make up his recipe (barley, corn and rye), the water from the
                underground Lynchburg cave, and a unique yeast for the fermentation of malt.</p>
              <br>
              <br>
              <h4 class="card-text text-center">€45EUR</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag("drinks/6.png", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
            <div class="card-body">
              <h2>Chivas</h2>
              <p class="card-text">Chivas Regal 12 Year Old: blend based on aged whiskeys of at least 12 years old. It
                is a soft drink with an aged and sweet taste.</p>
              <br>
              <br>
              <br>
              <h4 class="card-text text-center">€25EUR</h4>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag("drinks/7.jpg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
            <div class="card-body">
              <h2>Diplomático</h2>
              <p class="card-text">It is a balanced composition of complex rums distilled in copper stills and light
                rums distilled in columns, made from sugar cane molasses and molasses.</p>
              <br>
              <br>
              <br>
              <h4 class="card-text text-center">€52EUR</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag("drinks/8.jpg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
            <div class="card-body">
              <h2>Buchanans</h2>
              <p class="card-text">Buchanan’s signature mild and delicate flavor was born 135 years ago, when James
                Buchanan, a leading entrepreneur, created the refined blend that is recognized and appreciated to this
                day.</p>
              <br>
              <br>

              <h4 class="card-text text-center">€55EUR</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag("drinks/9.jpg", :alt => "2", class: "card-img-top", alt: "Thumbnail [100%x225]", style:"height: 425px; width: 100%; display: block;" )%>
            <div class="card-body">
              <h2>Cane Flower</h2>
              <p class="card-text">Cane Flower 25 Years rum is produced using only 100% natural ingredients, distilled
                up to five times to obtain maximum purity alcohol and aged under the 'Slow-Aged' process.</p>
              <br>
              <br>
              <br>
              <h4 class="card-text text-center">€32EUR</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina principal</title>
</head>
<body>
<main>
	<div class="container-fluid">
		<div class="carousel slide" id="main-carousel" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#main-carousel" data-slide-to="0" class="active"></li>
				<li data-target="#main-carousel" data-slide-to="1"></li>
				<li data-target="#main-carousel" data-slide-to="2"></li>
				
				
				
			</ol><!-- /.carousel-indicators -->
			
			<div class="carousel-inner">
				<div class="carousel-item active" id="imagen-carusel-1">
					<div class="carousel-caption">
                        <h1 id="carusel-letra-1">WestCoast</h1>
                        <p id="carusel-letra-1-1">The instant cut of time that we enjoy happily is important</p>
                    </div>
				</div>
				<div class="carousel-item" id="imagen-carusel-2">
					<div class="carousel-caption">
                    	<h1 id="carusel-letra-2">The best work product is the one that delivers the best results</h1>
                    </div>
				</div>
				<div class="carousel-item" id="imagen-carusel-3">
					<div class="carousel-caption">
                        <h1 id="carusel-letra-3">Let's remember the tools of those battles that make us heroes of war</h1>
                    </div>
				</div>
			</div><!-- /.carousel-inner -->
			
			<a href="#main-carousel" class="carousel-control-prev" data-slide="prev">
				<span class="carousel-control-prev-icon"></span>
				<span class="sr-only" aria-hidden="true">Prev</span>
			</a>
			<a href="#main-carousel" class="carousel-control-next" data-slide="next">
				<span class="carousel-control-next-icon"></span>
				<span class="sr-only" aria-hidden="true">Next</span>
			</a>
		</div><!-- /.carousel -->
	</div><!-- /.container -->
<br>
<br>
<br>
  <!-- clientes-->
    <section class="page-section bg-light" id="team">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Our Amazing Clients</h2>
                <h3 class="section-subheading text-muted">Every month we update the most outstanding opinions in our
                    customers.</h3>
            </div>
            <div class="row">
                <div class="col-lg-3">
                    <div class="team-member">
                        <%= image_tag("experiencias/2.jpg", class:"mx-auto rounded-circle")%>
						<h4>Kay Garland</h4>
                        <p class="text-muted">"WestCoast is brilliant for finding advertising knowledge and news
                            that actually matter. It’s truly a one-stop shop for helpful advertising information.".
                        </p>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="team-member">
                        <%= image_tag("experiencias/4.jpg", class:"mx-auto rounded-circle")%>
                        <h4>Bashful Sane.</h4>
                        <p class="text-muted">"The Trends section is exactly what we need and a great tool for us
                            to share new ideas & trends with our customers."</p>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="team-member">
                        <%= image_tag("experiencias/3.jpg", class:"mx-auto rounded-circle")%>
						<h4>Dan Hayes</h4>
                        <p class="text-muted">"WestCoast is ideal for a present at both the start of a project –
                            for ideas, inspiration and data – and at the end, as an independent product to help people
                            to have a product experience."</p>

                    </div>
                </div>
				<div class="col-lg-3">
                    <div class="team-member">
                        <%= image_tag("experiencias/1.jpg", class:"mx-auto rounded-circle")%>
                        <h4>Gemma Bale</h4>
                        <p class="text-muted">"We love WestCoast and actively use the premium products and case
                            studies to share with trends."</p>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 mx-auto text-center">
                    <p class="large text-muted">If you have already used our services we can also highlight your
                        experience with us, contact our advisors to be one of those who appears
                        previously.</p>
                </div>
            </div>
        </div>
    </section>
<div class="container-fluid">
	<div class="row">
		<div class="col-6">
			<img class="fluid float-left"><%= link_to image_tag("Historias/1.jpg", id:"img-1")%>
		</div>
		<div class="col-6">
			<h1 id="l-1">Hitoria 1</h1>
			<p id="l-1-1">Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic rerum accusantium, eos repellendus reiciendis id eius voluptatum, saepe, beatae dolor quo! Voluptate nisi mollitia temporibus architecto, dignissimos minima minus. Debitis?</p>
		</div>
	</div>
	<div class="row">
		<div class="col-6">
			<h1 id="l-2">Hitoria 2</h1>
			<p id="l-2-2">Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic rerum accusantium, eos repellendus reiciendis id eius voluptatum, saepe, beatae dolor quo! Voluptate nisi mollitia temporibus architecto, dignissimos minima minus. Debitis?</p>
		</div>
		<div class="col-6">
			<img class="fluid float-left"><%= link_to image_tag("Historias/4.jpg", id:"img-1")%>
		</div>
	</div>
	
</div>
<br>
<br>
<br>
<br>
<br>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
  <title>WestCoast</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<div class="container-fluid fixed-top" id="cabecera">
  <nav class="navbar navbar-expand-sm navbar-fluid">
    <a class="navbar-brand"><%= link_to image_tag("logo.jpeg", :alt => "logo", style: "height: 95px; width: 120px;"), root_path %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#uno" id="menu">
      <ion-icon name="menu-outline"></ion-icon>
    </button>
    <div class="collapse navbar-collapse" id="uno">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <h4 class="font-italic"><%= link_to "Inicio", root_path, class:"nav-link", id:"pepe" %></h4>
        </li>
        <li class="nav-item">
          <h4 class="font-italic"><%= link_to "Westcoast", westcoast_path, class:"nav-link", id:"pepe"  %></h4>
        </li>
        <li class="nav-item">
          <h4 class="font-italic"><%= link_to "Drink", drink_path, class:"nav-link", id:"pepe"  %></h4>
        </li>
        <li class="nav-item">
          <h4 class="font-italic "><%= link_to "Clothes", clothes_path, class:"nav-link", id:"pepe"  %></h4>
        </li>
        <%- if user_signed_in?%>
        <li>
          <h4 class="font-italic"><%= link_to "Mi Perfil", '#', class:"nav-link", id:"pepe"  %></h4>
        </li>
        <li>
          <h4 class="font-italic">
            <%= link_to "Salir", destroy_user_session_path, method: :delete, class:"nav-link", id:"pepe"  %></h4>
        </li>
        <% else %>
        <li>
          <h4 class="font-italic"><%= link_to "Log in", new_user_session_path, class:"nav-link", id:"pepe"  %></h4>
        </li>
        <% end %>
        <%- if administrator_signed_in? %>
        <li>
          <h4 class="font-italic"><%= link_to "Administrador", administrator_path,  class:"nav-link", id:"pepe"  %></h4>
        </li>
        <li>
          <h4 class="font-italic">
            <%= link_to "Salir", destroy_administrator_session_path, method: :delete, class:"nav-link", id:"pepe"  %>
          </h4>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>
<!--ESTILO DEL HEAD FIN-->
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<body>
  <%= yield %>

  <!-- Footer -->
  <footer class="font-italic page-footer pt-4" id="test">
    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left" id="piedepagina">
      <!-- Grid row -->
      <div class="row">
        <!-- Primera column -->
          <!-- Contacto -->
          <div class="col-md-6 mt-md-0 mt-3">
            <h5 class="text-uppercase">Contact</h5>
            <p>We would like to accompany you in your happy moments:</p>
            <br>
             <h6><span class="fa fa-globe fa-1x mb-1" aria-hidden="true"></span> information@westcoast.com</h6>
            </i>
          </div>
          <!-- Segunda column -->
          <!-- Tambien -->
          <div class="col-md-3 mb-md-0 mb-3">
            <h5 class="text-uppercase">Also</h5>
            <ul class="list-unstyled">
              <a class="btn btn-dark btn-social mx-2" href="#" id="logo"><i class="fab fa-instagram"></i></a>
            </ul>
          </div>
          <!-- Tercera column -->
          <!-- Aun no llamas -->
          <div class="col-md-3 mb-md-0 mb-3">
            <h5 class="text-uppercase">you still haven't called?</h5>
              <br>
               <h6><span class="fa fa-phone fa-1x mb-1" aria-hidden="true"></span>(+57)3000000000</h6>
          </div>

      </div>
    
      <div class="footer-copyright text-center py-3">
        © 2020 Copyright: WestCoast
      </div>

    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>


</body>

</html>